packages:
  - apps/*
  - packages/*

versions:
  '@types/jest': &types-jest 30.0.0
  '@types/node': &types-node 24.10.1
  eslint: &eslint 9.39.1
  jest: &jest 30.2.0
  nestjs: &nestjs 11.1.9
  node: &node 24.11.1
  pnpm: &pnpm 10.24.0
  prettier: &prettier 3.7.1
  rimraf: &rimraf 6.1.2
  turbo: &turbo 2.6.1
  typescript: &typescript 5.9.3

catalog:
  '@nestjs/common': *nestjs
  '@nestjs/core': *nestjs
  '@nestjs/platform-express': *nestjs
  '@nestjs/testing': *nestjs
  '@types/jest': *types-jest
  '@types/node': *types-node
  eslint: *eslint
  jest: *jest
  node: *node
  pnpm: *pnpm
  prettier: *prettier
  rimraf: *rimraf
  turbo: *turbo
  typescript: *typescript

ignoredBuiltDependencies:
  - '@nestjs/core'
  - unrs-resolver
